version: '2'
services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev_database
    ports:
      - "5433:5432"
  smtp:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"